# Generated by Django 3.2 on 2022-03-09 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=30)),
                ('street', models.CharField(max_length=60)),
                ('house', models.CharField(max_length=50)),
                ('flat', models.IntegerField(blank=True, max_length=10, null=True)),
                ('zip_code', models.IntegerField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Address', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='contacts.address')),
            ],
        ),
    ]
