# Generated by Django 3.2 on 2022-03-29 17:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github', models.CharField(blank=True, max_length=1024, null=True)),
                ('vk', models.CharField(blank=True, max_length=1024, null=True)),
                ('facebook', models.CharField(blank=True, max_length=1024, null=True)),
                ('instagram', models.CharField(blank=True, max_length=1024, null=True)),
                ('twitter', models.CharField(blank=True, max_length=1024, null=True)),
                ('website', models.CharField(blank=True, max_length=1024, null=True)),
                ('youtube', models.CharField(blank=True, max_length=1024, null=True)),
                ('mainLink', models.CharField(blank=True, max_length=1024, null=True)),
            ],
            options={
                'verbose_name_plural': 'Contacts',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lookingForAJob', models.BooleanField(blank=True, default=False, null=True)),
                ('lookingForAJobDescription', models.CharField(blank=True, max_length=2048, null=True)),
                ('photos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.contacts')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
