# Generated by Django 3.2 on 2022-03-29 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('small', models.CharField(blank=True, max_length=8000, null=True)),
                ('large', models.CharField(blank=True, max_length=8000, null=True)),
            ],
            options={
                'verbose_name_plural': 'Photos',
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='contacts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.contacts'),
        ),
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.photos'),
        ),
    ]
