# Generated by Django 3.2 on 2022-03-29 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20220329_2136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='photos',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='status',
        ),
        migrations.DeleteModel(
            name='Photos',
        ),
    ]
